### ISSUE TITLE
Some improvements / fixes

### ISSUE THREAD

**Issue by TonybynMp4** [JustLazzy/jl-carboost#16]
1:
If you crash, or leave the game you'll need to restart the boost (even tho the car is still here the boost isn't going on anymore)
2: 
let's say you're with a friend,
you will gain Rep but not him, (and also the thing in #1)
so I'd say maybe create a thing where you can have groups (like nopickles basically)?
3: 
maybe losing rep when you don't deliver and over time would be nice to keep the player interested even if he's at S+ so he still need to grind
4:
configurable rewards for each class would be cool, VIN scratch prices too
5: 
having to pay for normal boosts too to balance it out and not be 100% profit even if you lose the car

other than that it's great !

**Comment by Kentainfr** [comment]
1: The issue is known and we will try to solve it.
2: You win Reputation because you make the contract. Your friend isn’t in your group so that’s why he don’t get something. It’s a planned feature tho
And please don’t call NoPickles as example since most of them are just leak or just a copy of NoPixel. 
3:Losing rep will be only possible if you fail the contract and if you take too much time. Like said on discord it’s a planned feature too.
4:This feature is currently writes by our Lazzy Birds. You will be able to control the price of Vin for each class but you will also be able to control how much hacks is needed per tier.
5: The whole point of boosting is not to pay but have some risk. But I think we could add in the config to get the contract you must pay it. Will keep that in mind.

**Comment by TonybynMp4** [comment]
Thanks for the anwsers!
sorry that i didn't see the discord discussion (i guess it happened in the thread and since i mostly saw it as a support channel i didn't pay attention).
Anyway i'll be waiting impatiently for the future updates :)

And sorry, I didn't actually mean to reference to the nopickles tagged servers it's just how i've been calling NoPixel recently x)
>And please don’t call NoPickles as example since most of them are just leak or just a copy of NoPixel.
